### ISSUE TITLE
can't all be hidden

### ISSUE THREAD

**Issue by wangbaole0530** [ChenDaqian/WeChatCover#1]
Why can't all be hidden on the WeChat official account page？but chat pages can do  it

![image](https://github.com/ChenDaqian/WeChatCover/assets/50507317/38392632-1dec-4870-8d44-c94f2a5e2c03)
![image](https://github.com/ChenDaqian/WeChatCover/assets/50507317/6ca260b0-9a9c-471e-8011-9a211a6924cb)

**Comment by muxiang** [comment]
Fixed in Commit d5c34b1
