### ISSUE TITLE
Memory not immediately released

### ISSUE THREAD

**Issue by wangbaole0530** [ChenDaqian/WeChatCover#2]
When I repeatedly click on it, causing it to repeatedly lose focus and refocus, the memory usage will slowly increase, approximately to 1、2G, perhaps triggering GC and returning to 100M

![31171734e7572d8975158ab2cf4baf7](https://github.com/ChenDaqian/WeChatCover/assets/50507317/a927b630-541c-4b66-8416-214fbf91b777)

**Comment by Chendaqian** [comment]
This issue has been fixed in this submission
https://github.com/ChenDaqian/WeChatCover/commit/18d1e4dea24fd1283d1ecfa2c4f6ec672bdc1344
